CREATE TABLE themes(
id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT 'テーマID',
name VARCHAR(255) NOT NULL COMMENT 'テーマ名',
detail TEXT NOT NULL COMMENT 'テーマの詳細',
calendar_month DATE UNIQUE NOT NULL COMMENT 'カレンダーの月(YYYY-MM-DD)',
enable_dates TEXT NOT NULL COMMENT '登録可能な日',
created_user_id INTEGER NOT NULL COMMENT '登録されたユーザーID',
created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'テーマの登録日時',
updated_user_id INTEGER NOT NULL COMMENT '更新されたユーザーID',
updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'テーマの更新日時')
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE articles(
id INTEGER AUTO_INCREMENT COMMENT '記事のID',
calendar_date DATE NOT NULL COMMENT 'カレンダーの日(YYYY-MM-DD)',
user_id INTEGER NOT NULL COMMENT '記事を登録したユーザーID',
title TEXT NOT NULL COMMENT '記事のタイトル',
url TEXT COMMENT '記事のURL',
created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '記事の登録日時',
updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '記事の更新日時',
PRIMARY KEY (id),
UNIQUE (calendar_date),
INDEX user_id_index (user_id))
ENGINE=InnoDB DEFAULT CHARSET=utf8;